openapi: 3.0.0
info:
  description: >
    _This document describes the REST API of Ark Automate._
    Ark Automate is a platform that allows office users and software developers to automate business or everyday processes by simply sketching the steps of their process. By using simple flowcharts or powerful BPMN in their process outlines, users can create small software solutions using RPA that finish their tasks much faster and more reliably.
  version: 1.0.0
  title: Ark API
  license:
    name: LICENSE (MIT)
    url: https://github.com/bptlab/ark_automate

servers:
  - url: '{protocol}://{server}/api/v1'
    variables:
      protocol:
        default: https
        enum: [http, https]
      server:
        default: localhost:5000

tags:
  - name: RPA-Functionalities
    description: Operations about rpa supported applications, tasks and parameters
  - name: Robots
    description: Operations about robots

paths:
  #### RPA Functionalities ####
  #GET /rpa-framework/commands/get-available-applications
  /functionalities:
    get:
      tags:
        - RPA-Functionalities
      summary: Get all functionality objects including task, application and parameters
      operationId: getFunctionalities
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Functionalities'
  #// GET /rpa-framework/commands/get-available-tasks-for-application?application=Browser
  /functionalities/applications:
    get:
      tags:
        - RPA-Functionalities
      summary: Get all applications that ark automate supports
      operationId: getApplications
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Applications'
  #GET /rpa-framework/commands/getAllParameters
  /functionalities/{application}/tasks:
    parameters:
      - name: application
        in: path
        description: The name of an application
        required: true
        schema:
          $ref: '#/components/schemas/Applications'
    get:
      tags:
        - RPA-Functionalities
      summary: Gets all the tasks to execute for an application
      operationId: getTasks
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tasks'
        404:
          description: Not Found
  #### Robots ####
  # GET /ssot/:id
  /robots/{robotId}:
    parameters:
      - name: robotId
        in: path
        description: The id of a robot
        required: true
        schema:
          $ref: '#/components/schemas/RobotIds'
    get:
      tags:
        - Robots
      summary: Get a robot with a specific id
      operationId: getSpecificRobot
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Robots'
  # GET /renameRobot?id=78d09f66d2ed466cf20b06f7&newName=Bot+Browser
  /robots/{robotId}/robotName:
    parameters:
      - name: robotId
        in: path
        description: The id of a robot
        required: true
        schema:
          $ref: '#/components/schemas/RobotIds'
    patch:
      tags:
        - Robots
      summary: Updates the name of a robot
      operationId: setRobotName
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RobotNameObjects'
        description: Object with new robot name
        required: true
      responses:
        204:
          description: No Content
        400:
          description: Bad Request
  # // GET /shareRobotWithUser?userId=78d09f66d2ed466cf20b06f7&robotId=78d09f66d2ed466cf20b06f7
  /robots/userAccess:
    post:
      tags:
        - Robots
      summary: Share a robot with a user
      operationId: createUserAccessObject
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserAccessObjects'
        description: Object that connects a user with a robot
        required: true
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserAccessObjects'
        400:
          description: Bad Request

  # GET ssot/getAvailableRobotsForUser/78d09f66d2ed466cf20b06f7
  /robots/{userId}:
    parameters:
      - name: userId
        in: path
        description: The id of a user
        required: true
        schema:
          $ref: '#/components/schemas/ObjectIds'
    get:
      tags:
        - Robots
      summary: Get all robots for a specific user
      operationId: getRobotsForUser
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  required:
                    - _id
                    - robotName
                  properties:
                    _id:
                      $ref: '#/components/schemas/RobotIds'
                    robotName:
                      $ref: '#/components/schemas/RobotNames'

components:
  schemas:
    #### General ####
    ObjectIds:
      type: string
      minLength: 1
      example: 6061d5627dee5516b3824ade
    #### RPA-Functionalities ####
    Functionalities:
      type: object
      required:
        - _id
        - Application
        - Task
        - Code
      properties:
        _id:
          $ref: '#/components/schemas/ObjectIds'
        Application:
          $ref: '#/components/schemas/Applications'
        Task:
          $ref: '#/components/schemas/Tasks'
        Code:
          $ref: '#/components/schemas/Tasks'
        ouputValue:
          type: boolean
        inputVars:
          type: object
          required:
            - name
            - type
            - isRequired
            - infoText
            - index
          properties:
            name:
              type: string
              example: visible
            type:
              type: string
              example: Boolean
            isRequired:
              type: boolean
            infoText:
              type: string
              example: Show window after opening
            index:
              type: integer
              example: 0
    Applications:
      type: string
      example: Excel.Files
    Tasks:
      type: string
      example: Open Workbook
    #### Robots ####
    UserAccessObjects:
      type: object
      required:
        - AccessLevel
        - robotId
        - userId
      properties:
        AccessLevel:
          type: string
          example: ReadWrite
        robotId:
          $ref: '#/components/schemas/RobotIds'
        userId:
          $ref: '#/components/schemas/ObjectIds'
    RobotNameObjects:
      type: object
      required:
        - newRobotName
      properties:
        newRobotName:
          type: string
          minLength: 1
          example: Automating emails
    RobotIds:
      type: integer
      example: 606199015d691786a44a608f
    EventIds:
      type: string
      minLength: 1
      example: Event_0ay5426
    ActivityIds:
      type: string
      minLength: 1
      example: Activity_0ay5427
    ElementIds:
      type: string
      minLength: 1
      example: Event_0ay5426 or Activity_0ay5427
    RobotNames:
      type: string
      example: Automate morning emails
    RobotElements:
      type: object
      required:
        - predecessorIds
        - successorIds
        - _id
        - type
        - name
        - id
      properties:
        predecessorIds:
          type: array
          items:
            $ref: '#/components/schemas/ElementIds'
        successorIds:
          type: array
          items:
            $ref: '#/components/schemas/ElementIds'
        _id:
          $ref: '#/components/schemas/ObjectIds'
        type:
          type: string
          example: INSTRUCTION
        name:
          type: string
          example: Fill in current sales projections
        id:
          $ref: '#/components/schemas/ActivityIds'
    Robots:
      type: object
      required:
        - _id
        - robotName
      properties:
        _id:
          $ref: '#/components/schemas/RobotIds'
        starterId:
          $ref: '#/components/schemas/EventIds'
        robotName:
          $ref: '#/components/schemas/RobotNames'
        elements:
          type: array
          items:
            $ref: '#/components/schemas/RobotElements'
