name: Frontend testing

on:
  push:
    branches: [DEV, 279_refactor_folder_structure]
  pull_request:
    branches: [DEV]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{matrix.os}}

    strategy:
      max-parallel: 24
      matrix:
        node-version: [12.x, 14.x]
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
        working-directory: frontend
      - run: npm test
        working-directory: frontend
